name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - develop
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: bahmutov/npm-install@v1
        with:
          # By default, bahmutov/npm-install uses --frozen-lockfile
          install-command: yarn

      - name: Run tests and collect coverage
        run: yarn test --coverage

      - name: Typecheck
        run: yarn typecheck

      - name: Build
        run: yarn build

      - name: Run Codechecks
        run: yarn codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
        if: ${{ env.CC_SECRET != '' }}

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: >
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.head_commit.message, 'skip ci') &&
      !startsWith(github.event.head_commit.message, 'chore') &&
      !startsWith(github.event.pull_request.title, 'chore') && (
        github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name == github.repository
      )
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: bahmutov/npm-install@v1

      - name: Queue in release turnstile
        id: turnstyle
        continue-on-error: true
        uses: softprops/turnstyle@v1
        with:
          abort-after-seconds: 600

      - name: Create release
        if: steps.turnstyle.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_RELEASE_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN }}
        run: yarn release
